<?php

/**
 * Implements hook_menu().
 */
function foobar_menu() {
	// In general the path doesn't really matter since it is already registered in foobar.routing.yml
	$items['admin/foobar'] = array(
		'title' => 'Foobar',
		'description' => 'This is the demo foobar page.',
		// This is the name of the route from foobar.routing.yml
		'route_name' => 'foobar',
	);
  $items['admin/foobar/systemconfigformbase'] = array(
		'title' => 'SystemConfigFormBase Example',
		'description' => 'An example of a basic system configuration form using the SystemConfigFormBase class.',
		'route_name' => 'foobar.systemconfigformbase',
	);
  $items['foobar/form'] = array(
		'title' => 'Form Example',
		'description' => 'An example of a basic form.',
		'route_name' => 'foobar.form',
	);
  return $items;
}
